In [1]:
import pandas as pd
import os
import re

In [2]:
df = pd.read_csv('all_tpm.csv')
df = df.set_index('Gene')
df.head()

,WT_NoIL_Shock_rep1,WT_NoIL_Shock_rep2,WT_NoIL_Shock_rep3,WT_NoIL_Early_rep1,WT_NoIL_Early_rep2,WT_NoIL_Mid_rep1,WT_NoIL_Mid_rep2,WT_IL_Shock_rep1,WT_IL_Shock_rep2,WT_IL_Shock_rep3,...,MT_NoIL_Early_rep2,MT_NoIL_Early_rep3,MT_NoIL_Mid_rep1,MT_NoIL_Mid_rep2,MT_IL_Shock_rep1,MT_IL_Shock_rep2,MT_IL_Early_rep1,MT_IL_Early_rep2,MT_IL_Mid_rep1,MT_IL_Mid_rep2
Gene,,,,,,,,,,,,,,,,,,,,,
YALI0D08272g,1191.367449,1129.927281,1190.699866,1788.061496,1925.602855,2484.817791,2543.055038,1006.378542,967.981701,1025.130878,...,1537.31763,1550.994525,1630.929995,1719.564157,2087.754528,2013.643703,1467.416853,2398.19501,2255.496796,2134.508959
YalifMr30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
YalifMt32,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
YalifMt33,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
YalifMt34,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000

In [3]:
# Case 1:
write_path = os.path.join(os.path.abspath('.'),'1_WTIL_WTnoIL','input')

header_map = dict(
WT_t1='WT_IL_Early',
WT_t2='WT_IL_Mid',
MT_t1='WT_NoIL_Early',
MT_t2='WT_NoIL_Mid')

def write_fun(header_map, write_path):
    col_ids = [s for s in df.columns for l in list(header_map.values()) if l in s]
    subdf = df[col_ids]
    name_dict = {v: k for k, v in header_map.items()}
    subdf = subdf.rename(columns=lambda x: x.replace(x[:-5],name_dict[x[:-5]]))
    subdf.to_csv(os.path.join(write_path,'tpm.csv'))

    hm = pd.DataFrame({'INPUT_ID':list(header_map.keys()), 'ORIGINAL_ID':list(header_map.values())})
    hm.to_csv(os.path.join(write_path,'header_map.csv'), index=False)
    
write_fun(header_map, write_path)

In [4]:
# Case 2:
write_path = os.path.join(os.path.abspath('.'),'2_MTIL_MTnoIL','input')

header_map = dict(
WT_t1='MT_IL_Early',
WT_t2='MT_IL_Mid',
MT_t1='MT_NoIL_Early',
MT_t2='MT_NoIL_Mid')

write_fun(header_map, write_path)

In [5]:
# Case 3:
write_path = os.path.join(os.path.abspath('.'),'3_MTnoIL_WTnoIL','input')

header_map = dict(
WT_t1='MT_NoIL_Early',
WT_t2='MT_NoIL_Mid',
MT_t1='WT_NoIL_Early',
MT_t2='WT_NoIL_Mid')

write_fun(header_map, write_path)